### ISSUE TITLE
Looks like this repo is not active...

### ISSUE THREAD

**Issue by cunhaax** [whiskyechobravo/image_process#18]
This repo has lots of bugs, like images not being generated (sometimes - random error)
but there's a good alternative fork with lots of issues fixed, it is also available on PIP:

https://github.com/MinchinWeb/minchin.pelican.plugins.image_process

someone should put the forked repo on the pelican plugins list or integrate the fixes on this one

**Comment by Lucas-C** [comment]
PR: https://github.com/getpelican/pelican-plugins/pull/1171

**Comment by patrickfournier** [comment]
I added @Ecno92 as a maintainer to help me keep this repo up to date.

**Comment by Lucas-C** [comment]
Ok. Out of curiosity, do you plan to integrate the commits on the fork mentioned in this issue description ?

**Comment by Ecno92** [comment]
@Lucas-C I've reached out to @MinchinWeb by mail to check out if this is OK to do.

**Comment by MinchinWeb** [comment]
Hi! I'm happy to help maintain this fork rather than my own; no point in splitting efforts. Is this where I sign up? :)

One of the original issues that lead my to create my own fork is that I wanted the plugin available on PyPI. Partly so my [blog](https://github.com/MinchinWeb/blog.minchin.ca) could have a `requirements.txt` like everything else I do in Python, but more importantly, it allows me to consistently re-install an exact version, something that is hard to do when replying on the main `pelican-plugins` repo.

If we want support both a PyPI-able version and git-submodule-able version (for the `pelican-plugins` repo), then there is the question of repo layout. For PyPI (and Python packaging more generally), you'd put your source code (i.e. the plugin) in a subdirectory with all the support files (`setup.py`, `requirements.txt`, `README.rst`, etc) in the root directory. The `pelican-plugins` repo, however, generally assumes the plugin is in the root directory. I don't have a good solution to the above contradiction. Suggestions on how to deal with it?

**Comment by Ecno92** [comment]
@MinchinWeb 
I'm really in favor of only support installing through pip. 
It simplifies the way of working for both the developers as the users. 

However due to the activity in this repo and the amounts of references on GitHub I believe that this plugin is used by a reasonable amount of people. For that I suggest the following migration path:

1. create one commit which will be the last commit "old style". This includes a warning in the package which warns the user to upgrade.
2. release a new version to pypi dropping support for the old project structure.
3. submit a PR to pelican_plugins changing the commit reference of image_process to the commit mentioned above and a reference to the pypi page in the readme.

**Comment by Lucas-C** [comment]
I think this is related to https://github.com/getpelican/pelican-plugins/issues/213
The overall consensus in this issue is favorable to this kind of `pip`-based installation process.

If I understand you correctly @Ecno92, if we apply this plan than after that people relying on the `pelican-plugins` repo to use this plugin, and updating to the latest version of `pelican-plugins`, would **not** have their blog installation broken, right ? It would only be "stuck" to a fixed version of this repo code, with a warning displayed to encourage them to `pip install minchin.pelican.plugins.image_process` ?

This sounds like a reasonable plan, with one worrying detail to me thought: what will happen when our users will `pip install minchin.pelican.plugins.image_process` then ?
They will have **two** version of this plugin in their Python path, isn'it ?

**Comment by Ecno92** [comment]
@Lucas-C 
You are correct about the first thing.

About the second question: We indeed have to pick a new name to make sure that the right plugin version is loaded. 

I'm currently merging in @MinchinWeb's changes and simplifying the project a little bit so we can do a next release. 

I hope to finish it today, but I'm facing some issues with the test suite failing. So it may take a little bit longer.

**Comment by Lucas-C** [comment]
Ok, I see, the new plugin hosted on Pypi will have a different name than `image_process`.

Good luck with the merge !

**Comment by MinchinWeb** [comment]
> I'm really in favor of only support installing through pip.
> It simplifies the way of working for both the developers as the users.

Awesome! I agree.

> However due to the activity in this repo and the amounts of references on GitHub I believe that this plugin is used by a reasonable amount of people. For that I suggest the following migration path:
> 
>     1. create one commit which will be the last commit "old style". This includes a warning in the package which warns the user to upgrade.
> 
>     2. release a new version to pypi dropping support for the old project structure.
> 
>     3. submit a PR to pelican_plugins changing the commit reference of image_process to the commit mentioned above and a reference to the pypi page in the readme.

I like this approach. The only thing I would adjust is I would have a separate branch for the `pelican-plugins` repo to point to. I don't understand submodules as much as I would like, and so I'll often update them all in a go; have a separate branch will keep that from "accidentally" breaking the plugin via updating it too far. Also, a separate branch will make it easy to create updates, if needed, that only effect the `pelican-plugins` repo (like updates to the README).

> I'm currently merging in MinchinWeb's changes and simplifying the project a little bit so we can do a next release.
> 
> I hope to finish it today, but I'm facing some issues with the test suite failing. So it may take a little bit longer.

If you get stuck, feel free to post your current progress and I'm happy to help. The tests have been broken so long, don't get too hung up on that before showing your progress.

**Comment by Ecno92** [comment]
@MinchinWeb Last weekend I was able to fix the test suite and to clean up the project a little bit to be re-integrated with the main repository. 
Pending jobs include fixing the CI setup and the deploy to PyPi. 
I expect that I can finish this next Sunday.

**Comment by Lucas-C** [comment]
@Ecno92 What's the status of your work on this ? :)

I've just openend https://github.com/whiskyechobravo/image_process/pull/20 but it won't be needed if you publish this plugin Pypi and we remove the corresponding `git` submodule from `pelican-plugins`

**Comment by Ecno92** [comment]
@Lucas-C It's still on my mind! I was not able to continue my work yet as I had to spend time on other things. 
I hope to be able to pick it up soon enough. :)

**Comment by Ecno92** [comment]
A new version (v1.3.0) has been released at PyPi. 
https://pypi.org/project/pelican-image-process/
Take into account the instructions to make sure the Pelican can find the plugin.

I will now follow up with announcing the changes to the pelican-plugins repository. 

Things may have become broken even despite my testing efforts.

In case you find a problem please open an issue or open a pull request so we can release a next version.

**Comment by Lucas-C** [comment]
Good job ! Thanks

**Comment by Lucas-C** [comment]
Do you agree to remove the plugin from `pelican-plugins` ?

**Comment by MinchinWeb** [comment]
@Ecno92 Awesome work on getting this out the door!

I noticed that you dropped Travis-CI support; is that something you want help getting working again?

**Comment by Ecno92** [comment]
@MinchinWeb see https://github.com/whiskyechobravo/image_process/pull/21

Let's continue the discussions is separate issues as I consider this issue to be closed. :)
